# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter_reading',
            name='customer',
        ),
        migrations.AddField(
            model_name='meter_reading',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
        ),
    ]
