# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-14 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Units',
        ),
        migrations.AlterField(
            model_name='location',
            name='meter_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Meter_Reading'),
        ),
    ]
