# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-15 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200314_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter_reading',
            old_name='current_reading',
            new_name='control_reading',
        ),
        migrations.RemoveField(
            model_name='meter_reading',
            name='previous_reading',
        ),
        migrations.AddField(
            model_name='location',
            name='current_reading',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
