# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200316_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter_reading',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='meter_reading',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Meter_Reading'),
        ),
    ]
