# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200316_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='meter_reading',
        ),
        migrations.AddField(
            model_name='location',
            name='current_reading',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='date_read',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='initial_reading',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Meter_Reading',
        ),
    ]
