# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-15 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200315_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter_reading',
            name='date_read',
        ),
        migrations.AddField(
            model_name='location',
            name='date_read',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
