# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-15 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200315_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter_reading',
            old_name='control_reading',
            new_name='current_reading',
        ),
        migrations.RemoveField(
            model_name='location',
            name='current_reading',
        ),
        migrations.RemoveField(
            model_name='location',
            name='date_read',
        ),
        migrations.AddField(
            model_name='meter_reading',
            name='date_read',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='meter_reading',
            name='previous_reading',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
