# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200321_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter_Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_reading', models.PositiveIntegerField(default=0)),
                ('current_reading', models.PositiveIntegerField(default=0)),
                ('date_read', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='current_reading',
        ),
        migrations.RemoveField(
            model_name='location',
            name='date_read',
        ),
        migrations.RemoveField(
            model_name='location',
            name='initial_reading',
        ),
        migrations.RemoveField(
            model_name='location',
            name='units_consumed',
        ),
    ]
